-- Intentionally empty.
--
-- This migration was committed as a byte-for-byte duplicate of
-- 20260829102528_init. All of its schema changes, including removing
-- User.mobile and User_mobile_key and creating the property-related tables,
-- have already been applied by that preceding migration.
